[package]
name = "audiofi"
version = "0.1.0"
authors = ["AudioFi"]
license = "Apache-2.0"

[addresses]
audiofi = "0x5bf26c7f9e8e5c0d547e74baf079a072171dfe2051254fde4d5141059c938b68"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"
